version: "3.7"

services:
  backend:
    build: ./backend
  
  coderunner:
    build: ./coderunner
  
  frontend:
    build: ./frontend
  
  database:
    image: postgres:14
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres