version: "3.7"

services:
  backend:
    build: ./backend
    ports:
      - "8090:8090"
  
  coderunner:
    build: ./coderunner
    ports:
      - "8091:8091"
  
  frontend:
    build: ./frontend/leetcode
    ports:
      - "5000:3000"
      - "5001:15000"
  
  database:
    image: postgres:14
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres