version: "3.7"

services:
  backend:
    build: ./backend
    ports:
      - "8090:8090"
  
  coderunner:
    build: ./coderunner
    ports:
      - "8091:8091"
  
  frontend:
    build: ./frontend/leetcode
    ports:
      - "3000:3000"
      - "15000:15000"
  
  database:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./database:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=goleetcode
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres